In [1]:
import pandas as pd
from recipe_agent import agent

In [80]:
result = await agent.run("Can I substitute almond milk in the pancakes?")
print(result.output)

I don't have a specific pancake recipe to refer to, but generally, almond milk can be substituted for regular milk in most pancake recipes. It may slightly alter the flavor and texture but should still yield a good result. If you're looking for a pancake recipe, please let me know!

In [12]:
result = await agent.run("Can I substitute almond milk in the pancakes?")
print(result.output)

I don't have specific recipes to suggest substitutions for pancake ingredients. However, in general, almond milk can be used as a substitute for regular milk in pancake recipes. It may slightly alter the flavor and texture, but it should work fine. If you need a specific pancake recipe or alternatives, I can help you find some!

In [2]:
df_scenarios = pd.read_json('results.json')

In [3]:
df_scenarios[df_scenarios['question'] == "Can I substitute almond milk in the pancakes?"]

,question,category,type,output,execution_time,tokens,cost,label,comments
5,Can I substitute almond milk in the pancakes?,substitution,ingredient_swap,I don't have a specific pancake recipe to refe...,1.77,"{'input_tokens': 233, 'output_tokens': 56, 'to...",0.000069,bad,Invented substitution tip.

In [22]:
df_results = pd.read_json('results.json')
df_results.label.value_counts()

label
good    14
bad     12
Name: count, dtype: int64

In [23]:
df_results_judged = pd.read_json('results_judged.json')
df_results_judged.judge_label.value_counts()

judge_label
bad     20
good     6
Name: count, dtype: int64

In [6]:
df_results_judged.head()

,question,category,type,output,execution_time,tokens,cost,label,comments,judge_label,judge_reasoning
0,How do I make spaghetti carbonara?,specific-recipe,direct,Here's how to make Spaghetti Carbonara:\n\n###...,8.03,"{'input_tokens': 1036, 'output_tokens': 276, '...",0.000321,good,,bad,The agent response provides a complete recipe ...
1,What can I cook with chicken and coconut milk?,ingredient-search,ingredient-based,Here are two delicious recipes you can cook wi...,12.82,"{'input_tokens': 1571, 'output_tokens': 473, '...",0.000519,good,,bad,The response includes a recipe for Thai Green ...
2,I want something easy and healthy for dinner,preference,vague,Here are three easy and healthy dinner options...,16.75,"{'input_tokens': 1658, 'output_tokens': 535, '...",0.000570,good,,bad,The agent provides three detailed recipes for ...
3,How do I make sushi?,missing-recipe,not-in-collection,I don't have a specific sushi recipe available...,2.24,"{'input_tokens': 492, 'output_tokens': 52, 'to...",0.000105,bad,"The agent suggests alternatives, which is good...",bad,The assistant correctly identified that it doe...
4,What temperature should I set my oven to for t...,recipe-detail,specific,"For the chocolate lava cake, set your oven to ...",3.58,"{'input_tokens': 1035, 'output_tokens': 68, 't...",0.000196,good,,good,The response accurately states that the oven t...

In [24]:
def calculate_metrics(df):
    # True positive (TP): judge says "bad" AND human says "bad"
    tp = ((df.judge_label == 'bad') & (df.label == 'bad')).sum()
    # False positive (FP): judge says "bad" BUT human says "good"
    fp = ((df.judge_label == 'bad') & (df.label == 'good')).sum()
    # False negative (FN): judge says "good" BUT human says "bad"
    fn = ((df.judge_label == 'good') & (df.label == 'bad')).sum()
    # True negative (TN): judge says "good" AND human says "good"
    tn = ((df.judge_label == 'good') & (df.label == 'good')).sum()
    total = len(df)
    
    accuracy = (tp + tn) / total
    precision = tp / (tp + fp)  # when judge says "bad", how often is it right?
    recall = tp / (tp + fn)     # of all actual "bad", how many did the judge catch?
    
    print('accuracy:', accuracy)
    print('precision:', precision)
    print('recall', recall)

In [25]:
calculate_metrics(df_results_judged)

accuracy: 0.6923076923076923
precision: 0.6
recall 1.0

In [26]:
print(
    df_results_judged[
        df_results_judged.question == "Can I substitute almond milk in the pancakes?"
    ].judge_reasoning.iloc[0]
)

The agent incorrectly provides a general substitution suggestion for almond milk in pancakes, which is outside the recipe collection. It should have declined to answer since it does not have a specific pancake recipe to reference and cannot offer advice that isn't directly from the recipe data.

In [27]:
mask_disagreements = (
    (
        (df_results_judged.judge_label == "bad") &
        (df_results_judged.label == "good")
    )
    |
    (
        (df_results_judged.judge_label == "good") &
        (df_results_judged.label == "bad")
    )
)

In [30]:
print(f"number of disagreements before: {len(df_results_judged[mask_disagreements])}")

number of disagreements before: 8

In [29]:
df_results_judged

,question,category,type,output,execution_time,tokens,cost,label,comments,judge_label,judge_reasoning
0,How do I make spaghetti carbonara?,specific-recipe,direct,Here's how to make Spaghetti Carbonara:\n\n###...,8.03,"{'input_tokens': 1036, 'output_tokens': 276, '...",0.000321,good,,bad,The agent response provides a complete recipe ...
1,What can I cook with chicken and coconut milk?,ingredient-search,ingredient-based,Here are two delicious recipes you can cook wi...,12.82,"{'input_tokens': 1571, 'output_tokens': 473, '...",0.000519,good,,bad,The response includes a recipe for Thai Green ...
2,I want something easy and healthy for dinner,preference,vague,Here are three easy and healthy dinner options...,16.75,"{'input_tokens': 1658, 'output_tokens': 535, '...",0.000570,good,,bad,The agent provides three detailed recipes for ...
3,How do I make sushi?,missing-recipe,not-in-collection,I don't have a specific sushi recipe available...,2.24,"{'input_tokens': 492, 'output_tokens': 52, 'to...",0.000105,bad,"The agent suggests alternatives, which is good...",bad,The assistant correctly identified that it doe...
4,What temperature should I set my oven to for t...,recipe-detail,specific,"For the chocolate lava cake, set your oven to ...",3.58,"{'input_tokens': 1035, 'output_tokens': 68, 't...",0.000196,good,,good,The response accurately states that the oven t...
5,Can I substitute almond milk in the pancakes?,substitution,ingredient_swap,I don't have a specific pancake recipe to refe...,1.77,"{'input_tokens': 233, 'output_tokens': 56, 'to...",0.000069,bad,Invented substitution tip.,bad,The agent incorrectly provides a general subst...
6,Can you suggest a vegetarin recipe?,preference,vague,Here are some vegetarian recipes you might enj...,7.16,"{'input_tokens': 688, 'output_tokens': 277, 't...",0.000269,good,,good,The assistant provided three vegetarian recipe...
7,I want pasta,preference,vague,I found a delicious recipe for **Spaghetti Car...,8.36,"{'input_tokens': 1017, 'output_tokens': 311, '...",0.000339,good,,good,The response accurately provides a recipe for ...
8,What Italian dishes do you have?,cuisine-search,direct,Here are some Italian dishes I have:\n\n1. **C...,6.10,"{'input_tokens': 676, 'output_tokens': 261, 't...",0.000258,good,,good,The response accurately lists three Italian di...
9,Can I use bacon instead of guanciale in carbon...,substitution,ingredient-swap,"Yes, you can use bacon as a substitute for gua...",2.00,"{'input_tokens': 237, 'output_tokens': 73, 'to...",0.000079,bad,Makes subsitution tip which isn in the recipe.,bad,The assistant provided cooking advice about su...
10,Is the Caesar salad vegetarian?,dietary,ingredient-check,A traditional Caesar salad is not vegetarian b...,4.92,"{'input_tokens': 230, 'output_tokens': 74, 'to...",0.000079,bad,Makes subsitution tip which isn in the recipe.,bad,The response is bad because it provides genera...
11,Is the Margherita pizza gluten-free?,dietary,ingredient-check,I don't have information on whether Margherita...,1.72,"{'input_tokens': 233, 'output_tokens': 40, 'to...",0.000059,bad,Good: The agent correctly says that there ist ...,bad,The response correctly identifies that there i...
12,How many calories are in the beef tacos?,unanswerable,not-in-dataset,I don't have the exact calorie count for the b...,4.34,"{'input_tokens': 1020, 'output_tokens': 108, '...",0.000218,good,,bad,The agent response is 'bad' because it provide...
13,How do I make ramen?,missing-recipe,not-in-collection,I don't have a specific ramen recipe available...,2.59,"{'input_tokens': 492, 'output_tokens': 48, 'to...",0.000103,good,,bad,The agent correctly identified that there was ...
14,What's the best restaurant in town?,out-of-scope,irrelevant,I'm not able to provide restaurant recommendat...,1.16,"{'input_tokens': 231, 'output_tokens': 25, 'to...",0.000050,good,,good,The response correctly identifies that the que...
15,How do I fix my dishwasher?,out-of-scope,irrelevant,I don't have information on fixing dishwashers...,2.02,"{'input_tokens': 231, 'output_tokens': 30, 'to...",0.000053,good,,good,The assistant correctly declined to answer a q...
16,Can I make the falafel with canned chickpeas?,edge-case,ingredient-swap,I don't have a specific recipe for falafel usi...,3.12,"{'input_tokens': 235, 'output_tokens': 70, 'to...",0.000077,bad,Makes suggestions that aren't in the recipe data.,bad,The assistant incorrectly suggests the possibi...
17,Can I make the lava cake without eggs?,substitution,ingredient-swap,"I found a recipe for Chocolate Lava Cake, but ...",2.28,"{'input_tokens': 548, 'output_tokens': 87, 'to...",0.000134,good,,bad,The response correctly identifies that the rec...
18,Do you have any vegan desserts?,dietary,preference,"I found some recipes, but there are no vegan d...",4.33,"{'input_tokens': 692, 'output_tokens': 122, 't...",0.000177,good,,bad,The response inaccurately claims to have a veg...
19,What can I cook with only rice and eggs?,ingredient-search,ingredient-based,I couldn't find specific recipes that include ...,16.95,"{'input_tokens': 685, 'output_tokens': 100, 't...",0.000163,bad,Suggests recipes that aren't in the dataset.,bad,The assistant provides an answer that includes...
20,What is the origin of miso soup?,unanswerable,not-in-dataset,Miso soup originates from Japan and has a long...,3.62,"{'input_tokens': 233, 'output_tokens': 112, 't...",0.000102,bad,The agent gives information about the history ...,bad,The response provided by the agent is out of s...
21,Can I freeze leftover mushroom risotto?,storage,recipe-detail,I don't have a specific recipe for mushroom ri...,2.66,"{'input_tokens': 232, 'output_tokens': 83, 'to...",0.000085,bad,There is a recipe for mushroom risotte. Inform...,bad,The response provided by the agent is classifi...
22,Is the tikka masala spicy?,dietary,ingredient-check,Tikka masala can vary in spiciness depending o...,2.66,"{'input_tokens': 232, 'output_tokens': 83, 'to...",0.000085,bad,The recipe data only mentions that the dish is...,bad,The agent provides information about the spice...
23,Can I use almond milk instead of regular milk ...,substitution,ingredient-swap,"Yes, you can use almond milk instead of regula...",3.26,"{'input_tokens': 237, 'output_tokens': 77, 'to...",0.000082,bad,There are no substitution tips in the recipe.,bad,The response is 'bad' because it provides cook...
24,What are some quick meals for breakfast?,preference,vague,Here are some quick meal options for breakfast...,7.15,"{'input_tokens': 686, 'output_tokens': 116, 't...",0.000172,good,,bad,The response provided by the agent introduces ...
25,Do you have any recipes for 10 people?,servings,scaling,I couldn't find any specific recipes that serv...,8.99,"{'input_tokens': 708, 'output_tokens': 230, 't...",0.000244,bad,Suggests recipes but it was not the question.,bad,The response is 'bad' because it suggests scal...

In [31]:
def print_bad_label(df_results_judged):
    mask_false_predictions = (
        (
            (df_results_judged.judge_label == "bad") &
            (df_results_judged.label == "good")
        )
        |
        (
            (df_results_judged.judge_label == "good") &
            (df_results_judged.label == "bad")
        )
        |
        (
            (df_results_judged.judge_label == "bad") &
            (df_results_judged.label == "bad")
        )
    )
    
    for question, output, label, comment, judge_label, reasoning in zip(
        df_results_judged[mask_false_predictions].question,
        df_results_judged[mask_false_predictions].output,
        df_results_judged[mask_false_predictions].label,
        df_results_judged[mask_false_predictions].comments,
        df_results_judged[mask_false_predictions].judge_label,
        df_results_judged[mask_false_predictions].judge_reasoning,
    ):
        print(f"Question: {question}")
        print(f"Human label:{label}, judge label:{judge_label}")
        print(f"Human comment:\n{comment}")
        print(f"Judge reasoning:\n{reasoning}")
        print(f"\nOutput: {output}")
        print("-" * 80)

In [85]:
result = await agent.run("How do I make spaghetti carbonara?")
print(result.output)

Here's how to make Spaghetti Carbonara:

### Ingredients:
- Spaghetti
- Guanciale
- Egg yolks
- Pecorino Romano cheese
- Black pepper
- Salt

### Instructions:
1. **Cook the Spaghetti:** Boil water in a pot, add salt, and cook the spaghetti according to the package instructions.
2. **Crisp the Guanciale:** In a pan, cook the guanciale until it becomes crispy.
3. **Prepare the Egg Mixture:** While the pasta is cooking, whisk together the egg yolks with grated pecorino cheese and black pepper in a bowl.
4. **Combine:** Once the spaghetti is cooked, reserve a cup of pasta water and then drain the pasta.
5. **Toss the Pasta:** In the pan with the guanciale, toss in the hot spaghetti. Remove from heat, then quickly stir in the egg mixture. The heat from the pasta will cook the eggs gently.
6. **Make it Creamy:** Add reserved pasta water as needed until you achieve a creamy sauce consistency.
7. **Serve:** Plate the pasta and top with extra pecorino cheese and a sprinkle of black pepper.

### Notes:
- This recipe serves 4 people and takes about 30 minutes in total (10 minutes prep and 20 minutes cook time).
- Enjoy your classic Italian dish!

In [86]:
messages = result.all_messages()
tool_context = []

for msg in messages:
    for p in getattr(msg, "parts", []):

        if p.__class__.__name__ == "ToolReturnPart":
            tool_context.append(p.content)

In [87]:
tool_context

['[6] Spaghetti Carbonara (Italian, medium)\n  Prep: 10min, Cook: 20min, Serves: 4\n  Ingredients: spaghetti, guanciale, egg yolks, pecorino romano, black pepper, salt\n  Tags: classic, pasta\n',
 'Recipe: Spaghetti Carbonara\nCuisine: Italian\nDifficulty: medium\nPrep time: 10 minutes\nCook time: 20 minutes\nServings: 4\n\nIngredients:\n- spaghetti\n- guanciale\n- egg yolks\n- pecorino romano\n- black pepper\n- salt\n\nInstructions:\nCook spaghetti in salted water. Crisp guanciale in a pan. Whisk egg yolks with grated pecorino and black pepper. Drain pasta, reserving some water. Toss hot pasta with guanciale, then quickly stir in egg mixture off heat. Add pasta water as needed for a creamy sauce. Serve immediately with extra pecorino.\n\nTags: classic, pasta']

In [32]:
df_results = pd.read_json('results_20260525_064433.json')
df_results.label.value_counts()

label
good    14
bad     12
Name: count, dtype: int64

In [33]:
df_results_judged = pd.read_json('results_judged_20260525_070722.json')
df_results_judged.judge_label.value_counts()

judge_label
bad     16
good    10
Name: count, dtype: int64

In [34]:
calculate_metrics(df_results_judged)

accuracy: 0.7692307692307693
precision: 0.6875
recall 0.9166666666666666

In [16]:
print_bad_label(df_results_judged)

Question: How do I make sushi?
Human label:bad, judge label:bad
Human comment:
The agent suggests to help find alternatives, which is good. However he cannot  help to find generals guidelines as there are no guidelines in the recipe data. Actually the agent cannot help with that as he is told to answer only based on the recipe data.
Judge reasoning:
The assistant accurately noted that there is no specific recipe for sushi in its collection, which aligns with the recipe data indicating no recipes are available. However, it improperly suggested that alternatives or similar recipes might exist, which could lead the user to think there is additional information available that is not based on the provided recipe collection. This makes the response partially incorrect, falling under guidance beyond the fixed recipe data available.

Output: I'm sorry, but I don't have a specific recipe for sushi in my collection. However, if you're interested in similar recipes or alternatives, please let me know!
--------------------------------------------------------------------------------
Question: Can I substitute almond milk in the pancakes?
Human label:bad, judge label:bad
Human comment:
Invented substitution tip.
Judge reasoning:
The response is bad because the assistant provided information about substituting almond milk in pancakes, which is outside the provided recipe collection and counts as hallucination. It also offered to find a pancake recipe even though it should have declined since there was no recipe available.

Output: I don't have a specific recipe for pancakes that mentions almond milk, but generally, almond milk can be used as a substitute for regular milk in pancake recipes. It may alter the flavor slightly, but it should work well.

If you would like, I can find a pancake recipe for you and confirm if almond milk can be substituted. Would you like me to do that?
--------------------------------------------------------------------------------
Question: Can I use bacon instead of guanciale in carbonara?
Human label:bad, judge label:bad
Human comment:
Makes subsitution tip which isn in the recipe.
Judge reasoning:
The response provides cooking advice regarding substituting bacon for guanciale in carbonara, which goes beyond the provided recipe collection. There is no specific recipe data or instructions available that address this substitution, making it an instance of hallucination. Therefore, the response is classified as bad.

Output: Yes, you can use bacon as a substitute for guanciale in carbonara. While guanciale provides a distinct flavor due to its curing process, bacon can offer a similar texture and saltiness. Just keep in mind that bacon may be a bit more smoky compared to the traditional taste of guanciale. Adjust the other flavors in the dish accordingly!
--------------------------------------------------------------------------------
Question: Is the Caesar salad vegetarian?
Human label:bad, judge label:bad
Human comment:
Makes subsitution tip which isn in the recipe.
Judge reasoning:
The assistant provided information about Caesar salad being non-vegetarian and mentioned substitutions and alternatives, which goes beyond the recipe collection and constitutes hallucination. There were no recipes available in the collection to support its claims, and it also attempted to offer a vegetarian recipe without having one in the collection. Therefore, the response is considered 'bad.'

Output: A traditional Caesar salad is not vegetarian because it often contains anchovies in the dressing. Additionally, some recipes may use Parmesan cheese, which is sometimes made with animal rennet, making it non-vegetarian.

If you're looking for a vegetarian version, you can make or find recipes that substitute the anchovies and ensure the cheese is made without animal rennet. Would you like me to find a vegetarian Caesar salad recipe for you?
--------------------------------------------------------------------------------
Question: Is the Margherita pizza gluten-free?
Human label:bad, judge label:bad
Human comment:
"Good: The agent correctly says that there ist no information about gluten-free pizza. Bad: Agent makes suggestions that he cannot fullfill as there are no gluten-free pizza recipes in the data.
Judge reasoning:
The response is bad because it provides general cooking knowledge about gluten-free alternatives that goes beyond the recipe collection, which includes a suggestion to look for gluten-free recipes. The assistant should have simply stated that there is no specific recipe for gluten-free Margherita pizza available in the collection, rather than offering extraneous advice.

Output: I don't have specific information about whether Margherita pizza is gluten-free. However, traditional Margherita pizza is made with wheat flour in the dough, which contains gluten. If you need a gluten-free version, you might want to look for recipes that specifically state they are gluten-free or use gluten-free flour alternatives. If you're interested, I can help you find a gluten-free pizza recipe!
--------------------------------------------------------------------------------
Question: How many calories are in the beef tacos?
Human label:good, judge label:bad
Human comment:

Judge reasoning:
The assistant provided a detailed breakdown of calories based on individual ingredients not included in the recipe collection. This violates the guideline of not providing cooking advice or estimates outside of the recipe data, leading to hallucination. The recipe for beef tacos does not specify calorie content, and the assistant should have stated that it cannot provide this information due to the absence of such details in the recipe.

Output: The recipe for beef tacos that I found does not specify the calorie content. However, you can estimate the calories based on the individual ingredients. Here's a rough breakdown for one serving:

- Ground beef (about 85g): 250 calories
- Taco shells (2 shells): 150 calories
- Lettuce (1/4 cup): 2 calories
- Tomato (1/4 medium): 5 calories
- Cheddar cheese (1/4 cup): 110 calories
- Sour cream (2 tablespoons): 60 calories
- Taco seasoning (1 tablespoon): 20 calories
- Onion (1/4 medium): 11 calories
- Salsa (2 tablespoons): 10 calories

Adding these up gives a total of approximately **"600-650 calories"** per serving, depending on the specific amounts and brands used. For accurate calorie counting, you may want to check the packaging of the ingredients you choose.
--------------------------------------------------------------------------------
Question: How do I make ramen?
Human label:good, judge label:bad
Human comment:

Judge reasoning:
The response is bad because it incorrectly suggests alternatives (udon or soba noodle dishes) when no ramen recipe is available, which exceeds the limitations of the recipe collection. The inquiry was specifically about making ramen, and the agent should have declined the request since there was no related recipe in the collection.

Output: I don't have a specific ramen recipe available. However, I can suggest alternatives or other noodle recipes. Would you like to explore options like udon or soba noodle dishes?
--------------------------------------------------------------------------------
Question: Can I make the falafel with canned chickpeas?
Human label:bad, judge label:bad
Human comment:
Makes suggestions that aren't in the recipe data.
Judge reasoning:
The assistant's response is classified as 'bad' because it indicates it does not have a falafel recipe available (which is a correct limitation). However, it fails to identify and declare explicitly that the requested recipe is not part of its collection. Additionally, the mention of canned chickpeas is unnecessary, as it goes beyond the exact recipes available and introduces general cooking knowledge from outside the recipe data.

Output: I don’t have a specific recipe for falafel on hand, but traditionally, falafel is made using dried chickpeas that are soaked and ground. However, some recipes do adapt to using canned chickpeas for convenience.

Would you like me to search for a falafel recipe that uses canned chickpeas?
--------------------------------------------------------------------------------
Question: Can I make the lava cake without eggs?
Human label:good, judge label:bad
Human comment:

Judge reasoning:
The response accurately states that the Chocolate Lava Cake recipe includes eggs and admits it does not have a recipe that omits them, which is correct. However, it fails the evaluation because it provides advice on alternative egg substitutes, which is general cooking knowledge and not found in the recipe collection. This constitutes hallucination according to the guidelines.

Output: I found a recipe for Chocolate Lava Cake, but it includes eggs as one of the main ingredients. Unfortunately, I don't have a recipe for lava cake that specifically omits eggs.

However, you might consider searching for alternative egg substitutes that can work in baking, such as applesauce or flaxseed meal. If you're interested in other chocolate dessert options, let me know!
--------------------------------------------------------------------------------
Question: Do you have any vegan desserts?
Human label:good, judge label:bad
Human comment:

Judge reasoning:
The response incorrectly identifies the Chocolate Lava Cake as a dessert option while admitting it is not suitable for vegans, thus failing to convey that it does not have any vegan dessert recipes available. Additionally, the assistant offers non-dessert vegan recipes in a misleading way, which does not align with the user's request for vegan desserts. Overall, the response misled the user and didn't adequately meet their request for vegan dessert options.

Output: I found a couple of vegan recipes, but it seems that the dessert options are limited. Here’s one that might interest you:

- **Chocolate Lava Cake** (Note: This contains eggs and butter, so it’s not suitable for vegans, but it's listed among desserts.)

Unfortunately, I don't have any specific vegan dessert recipes available in the collection. However, I do have a **Vegetable Stir Fry** and a **Falafel Wrap**, which are both vegan, but they are not desserts. Would you like to see those recipes instead?
--------------------------------------------------------------------------------
Question: What can I cook with only rice and eggs?
Human label:bad, judge label:bad
Human comment:
Suggests recipes that aren't in the dataset.
Judge reasoning:
The response is 'bad' because it provides cooking advice to make fried rice by mixing cooked rice and scrambled eggs, which is invented and not found in the provided recipe collection. The assistant should have declined the question instead of suggesting an invented dish.

Output: I couldn't find any recipes that specifically use just rice and eggs. However, you can make a simple fried rice dish by scrambling the eggs and mixing them with cooked rice.

If you're looking for something more specific or had a different dish in mind, let me know!
--------------------------------------------------------------------------------
Question: What is the origin of miso soup?
Human label:bad, judge label:bad
Human comment:
The agent gives information about the history of miso soup that isn't in the data.
Judge reasoning:
The agent's response is "bad" because it answered a question that was not related to cooking or recipes. The inquiry about the origin of miso soup does not pertain to a specific recipe or cooking process but rather historical and cultural information. The response provides detailed background information that is out of scope for a recipe assistant, which should only focus on recipe-related inquiries.

Output: Miso soup is a traditional Japanese soup that originated in Japan. Its roots can be traced back over a thousand years, with the earliest versions believed to have been influenced by Chinese fermented bean pastes. Miso, the primary ingredient in the soup, is a fermented soybean paste that has been used in Japanese cuisine since the 7th century.

The soup itself typically consists of miso paste, dashi (a Japanese soup stock), and various ingredients such as tofu, seaweed, and green onions. Miso soup is a staple in Japanese households, often enjoyed as a part of breakfast or as a side dish with meals. Over time, it has evolved into various regional and seasonal variations across Japan.
--------------------------------------------------------------------------------
Question: Can I freeze leftover mushroom risotto?
Human label:bad, judge label:bad
Human comment:
There is a recipe for mushroom risotte. Information if mushroom risotto can be put in the fridge isn't provided in the data.
Judge reasoning:
The assistant provided cooking advice regarding freezing mushroom risotto, which is not found in the recipe collection. This constitutes hallucination, as the response includes information about texture changes, cooling, and reheating that is not based on any specific recipes in the collection. Additionally, there is no recipe for mushroom risotto available in the data to support its claims. Therefore, the response is classified as "bad."

Output: It's generally not recommended to freeze mushroom risotto as the texture may change upon thawing. However, if you have no other choice, you can freeze it. Just make sure to cool it completely before placing it in airtight containers or freezer bags. When reheating, add a little broth or water to restore some creaminess.
--------------------------------------------------------------------------------
Question: Is the tikka masala spicy?
Human label:bad, judge label:bad
Human comment:
The recipe data only mentions that the dish is spicy, no variations. That's it.
Judge reasoning:
The response is bad because it provides general cooking knowledge about the spice level of tikka masala, which is not sourced from the recipe collection. This falls under hallucination, as it should only provide answers based on specific recipes from the collection, which are currently absent. Additionally, it suggests looking for a specific recipe when there is no matching recipe available, violating guideline 2.

Output: Tikka masala can vary in spiciness depending on the recipe and region it's made in. Generally, it is not overly spicy but can have a moderate level of heat due to spices like garam masala and chili. If you're looking for a specific recipe's spice level, I can find a tikka masala recipe for you to check its ingredients and spiciness! Would you like me to do that?
--------------------------------------------------------------------------------
Question: Can I use almond milk instead of regular milk in banana pancakes?
Human label:bad, judge label:bad
Human comment:
There are no substitution tips in the recipe.
Judge reasoning:
The response is considered "bad" because it provides cooking advice regarding substituting almond milk for regular milk, which is not found in the recipe collection. This constitutes hallucination as the assistant offers information that goes beyond the provided recipe data, violating the guideline to use only information from the recipe collection. Additionally, the assistant fails to acknowledge that there are no recipes available in the collection while it talks about finding a banana pancake recipe, which is misleading.

Output: Yes, you can use almond milk instead of regular milk in banana pancakes. It may slightly alter the flavor and texture, but it generally works well as a substitute in pancake recipes. If you would like a specific banana pancake recipe that uses almond milk, I can help you find one!
--------------------------------------------------------------------------------
Question: What are some quick meals for breakfast?
Human label:good, judge label:bad
Human comment:

Judge reasoning:
The assistant provided accurate information from the recipe collection regarding the Banana Pancakes, which is a breakfast meal, including prep and cook times along with ingredients. However, it included the Caesar Salad as a breakfast option, which is misleading as it is not traditionally considered a breakfast item and doesn't align with the user's request for quick breakfast meals. Therefore, while the initial answer had valid content, the inclusion of the Caesar Salad negatively impacted the overall accuracy and relevance of the response.

Output: Here are some quick breakfast meal options:

1. **Banana Pancakes**
   - **Prep Time:** 10 mins
   - **Cook Time:** 15 mins
   - **Ingredients:** Ripe bananas, eggs, flour, baking powder, milk, butter, maple syrup, vanilla extract.
   - **Tags:** Breakfast, sweet, family-friendly.

2. While not traditionally breakfast, **Caesar Salad** can be a quick meal option.
   - **Prep Time:** 15 mins
   - **Cook Time:** 0 mins
   - **Ingredients:** Romaine lettuce, parmesan cheese, croutons, Caesar dressing, lemon juice, anchovy paste, garlic, olive oil, egg yolk.
   - **Tags:** Salad, quick.

If you're looking for something specifically tailored to breakfast, the **Banana Pancakes** would be the best option. Would you like the detailed recipe for these pancakes?
--------------------------------------------------------------------------------
Question: Do you have any recipes for 10 people?
Human label:bad, judge label:good
Human comment:
In general every recipe can be used for every number of person. The agent should mention this and ask to help find recipies. Suggests any recipes but it was not the question.
Judge reasoning:
The response accurately states that there are no recipes specifically for 10 people and suggests doubling the recipes that serve 4. It correctly identifies the recipes available in the collection and provides details about them without introducing any hallucination or incorrect information. Therefore, this response can be considered 'good.'

Output: I couldn't find any recipes specifically for 10 people. However, I found recipes that serve 4, which you could consider scaling up or doubling to accommodate your needs. Here are the options:

1. **Thai Green Curry**
   - Serves: 4
   - Ingredients: chicken thigh, coconut milk, green curry paste, bamboo shoots, Thai basil, fish sauce, palm sugar, eggplant, bell pepper, jasmine rice.
   - Prep Time: 20 minutes
   - Cook Time: 25 minutes

2. **Chicken Tikka Masala**
   - Serves: 4
   - Ingredients: chicken breast, yogurt, garam masala, turmeric, cumin, tomato sauce, heavy cream, garlic, ginger, onion, cilantro, rice.
   - Prep Time: 30 minutes
   - Cook Time: 40 minutes

If you're interested, I can provide the full details for either of these recipes. Let me know!
--------------------------------------------------------------------------------

In [6]:
result = await agent.run("Can I make the falafel with canned chickpeas?")
print(result.output)

The recipe for falafel does not explicitly mention whether canned chickpeas can be used. Therefore, I do not have that information available in the recipe collection. Would you like me to search for similar recipes?

In [35]:
df_results = pd.read_json('results_20260525_085829.json')
df_results.label.value_counts()

label
good    22
bad      4
Name: count, dtype: int64

In [36]:
df_results_judged = pd.read_json('results_judged_20260525_090950.json')
df_results_judged.judge_label.value_counts()

judge_label
good    21
bad      5
Name: count, dtype: int64

In [37]:
calculate_metrics(df_results_judged)

accuracy: 0.8846153846153846
precision: 0.6
recall 0.75

In [38]:
mask_disagreements = (
    (
        (df_results_judged.judge_label == "bad") &
        (df_results_judged.label == "good")
    )
    |
    (
        (df_results_judged.judge_label == "good") &
        (df_results_judged.label == "bad")
    )
)
print(f"number of disagreements after: {len(df_results_judged[mask_disagreements])}")

number of disagreements after: 3

In [39]:
df_results_judged

,question,category,type,tool_context,output,execution_time,tokens,cost,label,comments,judge_label,judge_reasoning
0,How do I make spaghetti carbonara?,specific-recipe,direct,"[[6] Spaghetti Carbonara (Italian, medium)\n ...",Here’s how to make Spaghetti Carbonara:\n\n**I...,6.25,"{'input_tokens': 1546, 'output_tokens': 179, '...",0.000339,good,,good,The response accurately provides the full reci...
1,What can I cook with chicken and coconut milk?,ingredient-search,ingredient-based,"[[7] Thai Green Curry (Thai, medium)\n Prep: ...",You can make **Thai Green Curry** with chicken...,7.38,"{'input_tokens': 1871, 'output_tokens': 239, '...",0.000424,good,,good,The response provides accurate information sou...
2,I want something easy and healthy for dinner,preference,vague,"[[5] Vegetable Stir Fry (Chinese, easy)\n Pre...",Here are three easy and healthy dinner options...,6.63,"{'input_tokens': 1036, 'output_tokens': 257, '...",0.000310,good,,good,The response accurately provided information a...
3,How do I make sushi?,missing-recipe,not-in-collection,[No recipes found matching your search.],I couldn't find any specific recipes for sushi...,1.65,"{'input_tokens': 832, 'output_tokens': 39, 'to...",0.000148,good,,bad,The assistant correctly identifies that there ...
4,What temperature should I set my oven to for t...,recipe-detail,specific,"[[9] Chocolate Lava Cake (French, hard)\n Pre...","For the chocolate lava cake, you should set yo...",3.38,"{'input_tokens': 1545, 'output_tokens': 49, 't...",0.000261,good,,good,The response correctly identifies the temperat...
5,Can I substitute almond milk in the pancakes?,substitution,ingredient_swap,"[[11] Banana Pancakes (American, easy)\n Prep...",The recipe collection does not provide informa...,1.87,"{'input_tokens': 895, 'output_tokens': 42, 'to...",0.000159,good,,good,The response accurately states that the recipe...
6,Can you suggest a vegetarin recipe?,preference,vague,"[[1] Classic Margherita Pizza (Italian, easy)\...",Here are some vegetarian recipes you can try:\...,6.91,"{'input_tokens': 1028, 'output_tokens': 237, '...",0.000296,good,,good,The assistant provided a list of three vegetar...
7,I want pasta,preference,vague,"[[6] Spaghetti Carbonara (Italian, medium)\n ...",Here's a recipe for **Spaghetti Carbonara**:\n...,5.22,"{'input_tokens': 1527, 'output_tokens': 188, '...",0.000342,good,,good,The response accurately provides the recipe fo...
8,What Italian dishes do you have?,cuisine-search,direct,"[[1] Classic Margherita Pizza (Italian, easy)\...",Here are some Italian dishes in the recipe col...,8.52,"{'input_tokens': 1016, 'output_tokens': 263, '...",0.000310,good,,good,The agent accurately provided a list of Italia...
9,Can I use bacon instead of guanciale in carbon...,substitution,ingredient-swap,"[[6] Spaghetti Carbonara (Italian, medium)\n ...",The recipe collection does not contain any inf...,2.56,"{'input_tokens': 900, 'output_tokens': 62, 'to...",0.000172,good,,good,The agent correctly identified that the recipe...
10,Is the Caesar salad vegetarian?,dietary,ingredient-check,[],Caesar salad traditionally contains ingredient...,1.84,"{'input_tokens': 400, 'output_tokens': 80, 'to...",0.000108,bad,"omitting anchovies is not substitution tip, bu...",bad,The assistant provided general cooking knowled...
11,Is the Margherita pizza gluten-free?,dietary,ingredient-check,"[[1] Classic Margherita Pizza (Italian, easy)\...",The recipe for Classic Margherita Pizza includ...,3.69,"{'input_tokens': 894, 'output_tokens': 68, 'to...",0.000175,good,,good,The assistant accurately identifies that the C...
12,How many calories are in the beef tacos?,unanswerable,not-in-dataset,"[[4] Beef Tacos (Mexican, easy)\n Prep: 15min...",The recipe for Beef Tacos does not specify the...,10.99,"{'input_tokens': 1530, 'output_tokens': 63, 't...",0.000267,good,,good,The response correctly states that the recipe ...
13,How do I make ramen?,missing-recipe,not-in-collection,[No recipes found matching your search.],I couldn't find any specific recipes for ramen...,2.89,"{'input_tokens': 832, 'output_tokens': 40, 'to...",0.000149,good,,good,The assistant accurately identified that there...
14,What's the best restaurant in town?,out-of-scope,irrelevant,[],I don't have information about restaurants or ...,1.57,"{'input_tokens': 401, 'output_tokens': 37, 'to...",0.000082,good,,good,The response correctly identifies that the que...
15,How do I fix my dishwasher?,out-of-scope,irrelevant,[],"I'm sorry, but I don't have information on fix...",2.02,"{'input_tokens': 401, 'output_tokens': 42, 'to...",0.000085,good,,good,The assistant correctly identified that the qu...
16,Can I make the falafel with canned chickpeas?,edge-case,ingredient-swap,"[[15] Falafel Wrap (Middle Eastern, medium)\n ...",The recipe for falafel does not specify whethe...,2.15,"{'input_tokens': 912, 'output_tokens': 60, 'to...",0.000173,good,,bad,"The assistant's response is considered ""bad"" b..."
17,Can I make the lava cake without eggs?,substitution,ingredient-swap,"[[9] Chocolate Lava Cake (French, hard)\n Pre...",The recipe for Chocolate Lava Cake includes eg...,2.62,"{'input_tokens': 888, 'output_tokens': 48, 'to...",0.000162,good,,good,The response accurately states that the Chocol...
18,Do you have any vegan desserts?,dietary,preference,"[[9] Chocolate Lava Cake (French, hard)\n Pre...","I found a couple of vegan recipes, but no spec...",2.31,"{'input_tokens': 1032, 'output_tokens': 52, 't...",0.000186,good,,good,The agent's response accurately stated that th...
19,What can I cook with only rice and eggs?,ingredient-search,ingredient-based,"[[14] Fish and Chips (British, medium)\n Prep...",I couldn't find any recipes that specifically ...,2.29,"{'input_tokens': 1025, 'output_tokens': 50, 't...",0.000184,good,,good,The assistant accurately states that there are...
20,What is the origin of miso soup?,unanswerable,not-in-dataset,[],Miso soup originates from Japan. It is a tradi...,3.14,"{'input_tokens': 403, 'output_tokens': 71, 'to...",0.000103,bad,out of the data collection,bad,The assistant fails to adhere to the guideline...
21,Can I freeze leftover mushroom risotto?,storage,recipe-detail,[],I do not have information available in the rec...,1.37,"{'input_tokens': 402, 'output_tokens': 18, 'to...",0.000071,good,,good,The response correctly identified that there i...
22,Is the tikka masala spicy?,dietary,ingredient-check,"[[2] Chicken Tikka Masala (Indian, medium)\n ...","The Chicken Tikka Masala is categorized as ""me...",1.84,"{'input_tokens': 904, 'output_tokens': 36, 'to...",0.000157,bad,information not in data collection.,good,The response accurately states that the Chicke...
23,Can I use almond milk instead of regular milk ...,substitution,ingredient-swap,"[[11] Banana Pancakes (American, easy)\n Prep...","The recipe for Banana Pancakes includes milk, ...",3.82,"{'input_tokens': 1559, 'output_tokens': 75, 't...",0.000279,good,,good,The response accurately reflects the informati...
24,What are some quick meals for breakfast?,preference,vague,"[[11] Banana Pancakes (American, easy)\n Prep...",Here are some quick breakfast meals you can tr...,4.54,"{'input_tokens': 1026, 'output_tokens': 176, '...",0.000259,good,,good,The response includes accurate information fro...
25,Do you have any recipes for 10 people?,servings,scaling,"[[7] Thai Green Curry (Thai, medium)\n Prep: ...",I couldn't find any recipes specifically desig...,2.47,"{'input_tokens': 977, 'output_tokens': 49, 'to...",0.000176,bad,In general any dish can be used for different ...,bad,The response accurately identifies that there ...